/*export enum ActionTypes {
    ADD_TO_DO_LIST = 'ADD-TO-DO-LIST',
    DELETE_TO_DO_LIST = 'DELETE-TO-DO-LIST',
    CHANGE_TO_DO_LIST_TITLE = 'CHANGE-TO-DO-LIST-TITLE',
    CHANGE_TO_DO_LIST_FILTER_METHOD = 'CHANGE-TO-DO-LIST-FILTER-METHOD',
    ADD_TASK = 'ADD-TASK',
    DELETE_TASK = 'DELETE-TASK',
    CHANGE_TASK_TITLE = 'CHANGE-TASK-TITLE',
    CHANGE_TASK_COMPLETION = 'CHANGE-TASK-COMPLETION',
}*/

export const ADD_TO_DO_LIST = 'ADD-TO-DO-LIST';
export const DELETE_TO_DO_LIST = 'DELETE-TO-DO-LIST';
export const CHANGE_TO_DO_LIST_TITLE = 'CHANGE-TO-DO-LIST-TITLE';
export const CHANGE_TO_DO_LIST_FILTER_METHOD = 'CHANGE-TO-DO-LIST-FILTER-METHOD';
export const ADD_TASK = 'ADD-TASK';
export const DELETE_TASK = 'DELETE-TASK';
export const CHANGE_TASK_TITLE = 'CHANGE-TASK-TITLE';
export const CHANGE_TASK_COMPLETION = 'CHANGE-TASK-COMPLETION';